<?php

$peliculas = [
    [
        'nom' => 'Inception',
        'imatge' => 'https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2020/07/hipertextual-diez-anos-inception-extrana-mirada-nolan-sobre-realidad-siguevigente-2020650351-scaled.jpg?fit=2560%2C1440&quality=50&strip=all&ssl=1',
        'carrusel1'=>'https://i0.wp.com/imgs.hipertextual.com/wp-content/uploads/2020/07/hipertextual-diez-anos-inception-extrana-mirada-nolan-sobre-realidad-siguevigente-2020650351-scaled.jpg?fit=2560%2C1440&quality=50&strip=all&ssl=1',
        'carrusel2'=>'https://media.gq.com.mx/photos/5e582fec0c1d83000831acf6/master/pass/final-de-inception-explicado.jpg',
        'carrusel3'=>'https://revistamutaciones.com/wp-content/uploads/2020/06/origen-inception-christopher-nolan-mutaciones-1.jpg',
        'horaris' => '15:30/18:00/21:00',
        'sinopsi' => 'Un ladrón que roba secretos corporativos a través del uso de la tecnología de sueños compartidos es asignado a plantar una idea en la mente de un C.E.O.',
        'durada' => '148 min',
        'director' => 'Christopher Nolan',
        'repartiment' => 'Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page',
        'qualificacio' => '+16',
        'genere' => 'Ciencia ficción, Acción',
        'trailer_url' => 'https://www.youtube.com/embed/RV9L7ui9Cn8?si=L9XFA611_YJZ7X_R',
        'estrelles' => 3
    ],
    [
        'nom' => 'The Matrix',
        'imatge' => 'https://purodiseno.lat/wp-content/uploads/2021/06/Matrix-1-828x621.jpg',
        'carrusel1'=>'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2013/03/213846-cine-ciencia-ficcion-critica-matrix.jpg?tf=3840x',
        'carrusel2'=>'https://www.lavanguardia.com/andro4all/hero/2024/07/matrix.1722412526.9538.jpg?width=1200',
        'carrusel3'=>'https://ulia.org/diseloconcine/wp-content/uploads/2021/02/Matrix-y-morfeo.jpg',
        'horaris' => '14:00/17:30/20:00',
        'sinopsi' => 'Un hacker descubre que su realidad es una simulación creada por máquinas inteligentes.',
        'durada' => '136 min',
        'director' => 'Lana Wachowski, Lilly Wachowski',
        'repartiment' => 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss',
        'qualificacio' => '+16',
        'genere' => 'Ciencia ficción, Acción',
        'trailer_url' => 'https://www.youtube.com/embed/Pl_H2Lmjn6k?si=_Cv6Ok9Oxt017btB',
        'estrelles' => 4
    ],
    [
        'nom' => 'Parasite',
        'imatge' => 'https://media.gq.com.mx/photos/5e163a93a3ee270008aa3501/16:9/w_2560%2Cc_limit/parasite-datos-de-la-pelicula-que-esta-ganando-todos-los-premios-dos.jpg',
        'carrusel1'=>'https://media.gq.com.mx/photos/5e163a93a3ee270008aa3501/16:9/w_2560%2Cc_limit/parasite-datos-de-la-pelicula-que-esta-ganando-todos-los-premios-dos.jpg',
        'carrusel2'=>'https://media-front.elmostrador.cl/2020/01/parasitepeli%CC%81cula.jpg',
        'carrusel3'=>'https://i0.wp.com/www.conlosojosabiertos.com/wp-content/uploads/2020/02/parasite-1-1.jpg?fit=1300%2C650&ssl=1',
        'horaris' => '15:30/16:00/20:00',
        'sinopsi' => 'Una familia de bajos recursos se infiltra en la vida de una familia adinerada.',
        'durada' => '132 min',
        'director' => 'Bong Joon Ho',
        'repartiment' => 'Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong',
        'qualificacio' => '+16',
        'genere' => 'Drama, Thriller',
        'trailer_url' => 'https://www.youtube.com/embed/90dWVETAdtI?si=G-0dxsCMhpXuYmuH',
        'estrelles' => 5
    ],
    [
        'nom' => 'Joker',
        'imatge' => 'https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/e37195fe-c232-4ba0-bb9e-c4004279b6fa/4447958e-2d4f-4367-943d-0de4aaf38a82?host=wbd-images.prod-vod.h264.io&partner=beamcom',
        'carrusel1'=>'https://th.bing.com/th/id/OIP.6HmeLv-8z9ebLrIKwonIrwHaEK?rs=1&pid=ImgDetMain',
        'carrusel2'=>'https://straightfromamovie.com/wp-content/uploads/2019/10/joker-movie-wallpaper.jpg',
        'carrusel3'=>'https://cinemagavia.es/wp-content/uploads/2019/10/Joker-1.jpg',
        'horaris' => '15:30/17:00/21:00',
        'sinopsi' => 'Un hombre mentalmente inestable se convierte en el villano más temido de Gotham City.',
        'durada' => '122 min',
        'director' => 'Todd Phillips',
        'repartiment' => 'Joaquin Phoenix, Robert De Niro, Zazie Beetz',
        'qualificacio' => '+16',
        'genere' => 'Drama, Crimen',
        'trailer_url' => 'https://www.youtube.com/embed/ygUHhImN98w?si=uUlUXxb-QC8HGook',
        'estrelles' => 4
    ],
    [
        'nom' => 'Interstellar',
        'imatge' => 'https://beam-images.warnermediacdn.com/BEAM_LWM_DELIVERABLES/aa5b9295-8f9c-44f5-809b-3f2b84badfbf/8a7dd34b09c9c25336a3d850d4c431455e1aaaf0.jpg?host=wbd-images.prod-vod.h264.io&partner=beamcom',
        'carrusel1'=>'https://m.media-amazon.com/images/M/MV5BYmJkMjM3NTktYThjZS00YzQyLTlkMDMtZWU2Y2U1Mjc0ZWExL2ltYWdlXkEyXkFqcGdeQXVyNzE4NDc2Mjc@._V1_.jpg',
        'carrusel2'=>'https://www.moma.org/d/assets/W1siZiIsIjIwMTUvMTAvMTQvNm10bzI1bGt2NF96b29tXzE0MTkyNzA2OTlfaW50ZXJzdGVsbGFyXzJ4LmpwZyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ/zoom_1419270699_interstellar@2x.jpg?sha=eec9fc9c3b33b820',
        'carrusel3'=>'https://th.bing.com/th/id/OIP.gW6BCGs4QbnyG25ggsn_iwHaEo?rs=1&pid=ImgDetMain',
        'horaris' => '15:00/18:00/22:00',
        'sinopsi' => 'Un grupo de astronautas viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad.',
        'durada' => '169 min',
        'director' => 'Christopher Nolan',
        'repartiment' => 'Matthew McConaughey, Anne Hathaway, Jessica Chastain',
        'qualificacio' => '+16',
        'genere' => 'Ciencia ficción, Aventura',
        'trailer_url' => 'https://www.youtube.com/embed/UoSSbmD9vqc?si=IFl0EabPauRygXAJ',
        'estrelles' => 5
    ],
    [
        'nom' => 'La La Land',
        'imatge' => 'https://i0.wp.com/noisy.es/wp-content/uploads/2017/02/la-la-land-poster.jpeg?fit=945%2C532&ssl=1',
        'carrusel1'=>'https://th.bing.com/th/id/OIP.999KjVxi1RmOhuo1TIsJnQHaEK?rs=1&pid=ImgDetMain',
        'carrusel2'=>'https://thecinemaholic.com/wp-content/uploads/2018/03/la-la-land-5.jpg',
        'carrusel3'=>'https://th.bing.com/th/id/R.c2821de199fa5ae33aefdb22d4ac1e35?rik=HjcJXmUHIpADwQ&pid=ImgRaw&r=0',
        'horaris' => '15:30/18:10/21:30',
        'sinopsi' => 'Una historia de amor entre un músico de jazz y una aspirante a actriz en Los Ángeles.',
        'durada' => '128 min',
        'director' => 'Damien Chazelle',
        'repartiment' => 'Ryan Gosling, Emma Stone, John Legend',
        'qualificacio' => '+12',
        'genere' => 'Musical, Romance',
        'trailer_url' => 'https://www.youtube.com/embed/nRayUjXIDdQ?si=f4r7wmrp8cOBjt0-',
        'estrelles' => 4
    ],
    [
        'nom' => 'Avengers: Endgame',
        'imatge' => 'https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/DB176BD1488D7E4822256EF1778C124FC17388FC1E7F0F6D89B38AFF5FB001F6/scale?width=1200&aspectRatio=1.78&format=webp',
        'carrusel1'=>'https://th.bing.com/th/id/OIP.OoV1ELvpuVQprPCT_EuwFgHaEC?rs=1&pid=ImgDetMain',
        'carrusel2'=>'https://th.bing.com/th/id/OIP.NwFQQ-pG9w3y3tS4WjDifAHaEK?rs=1&pid=ImgDetMain',
        'carrusel3'=>'https://images.wallpapersden.com/image/download/chris-hemsworth-as-thor-in-endgame_a2tlamaUmZqaraWkpJRnZWVlrWZoZ24.jpg',
        'horaris' => '15:20/18:30/23:00',
        'sinopsi' => 'Los Vengadores restantes deben encontrar una manera de derrotar a Thanos y restaurar el universo.',
        'durada' => '181 min',
        'director' => 'Anthony Russo, Joe Russo',
        'repartiment' => 'Robert Downey Jr., Chris Evans, Mark Ruffalo',
        'qualificacio' => '+13',
        'genere' => 'Acción, Ciencia ficción',
        'trailer_url' => 'https://www.youtube.com/embed/UQ3bqYKnyhM?si=jSyDAaKjF8ndRVSp',
        'estrelles' => 4
    ],
    [
        'nom' => 'The Godfather',
        'imatge' => 'https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/06/73/23/1c.jpg',
        'carrusel1'=>'https://www.americamagazine.org/sites/default/files/main_image/2022/03/09/Godfather.jpg.jpg',
        'carrusel2'=>'https://a.ltrbxd.com/resized/sm/upload/zp/bn/1x/6r/the-godfather-1200-1200-675-675-crop-000000.jpg?v=397832feef',
        'carrusel3'=>'https://cinestudio.org/wp-content/uploads/2023/06/The-Godfather-Long.jpeg',
        'horaris' => '15:30/18:00/21:00',
        'sinopsi' => 'La historia de la familia Corleone, una de las más poderosas dentro del crimen organizado en los EE.UU.',
        'durada' => '175 min',
        'director' => 'Francis Ford Coppola',
        'repartiment' => 'Marlon Brando, Al Pacino, James Caan',
        'qualificacio' => '+16',
        'genere' => 'Drama, Crimen',
        'trailer_url' => 'https://www.youtube.com/embed/UaVTIH8mujA?si=ezxIyQng7a2f_4_C',
        'estrelles' => 5
    ],
    [
        'nom' => 'Fight Club',
        'imatge' => 'https://hips.hearstapps.com/hmg-prod/images/fight-club-1-1571084249.jpg?crop=1xw:0.7436194895591647xh;center,top&resize=1200:*',
        'carrusel1'=>'https://image.tmdb.org/t/p/original/pCUdYAaarKqY2AAUtV6xXYO8UGY.jpg',
        'carrusel2'=>'https://th.bing.com/th/id/R.4b81bf366cc5a12840db2849995c0fbd?rik=Vax2Pwfp5baiYQ&pid=ImgRaw&r=0',
        'carrusel3'=>'https://imgsrc.cineserie.com/2022/11/le-narrateur-edward-norton-fight-club.png?ver=1',
        'horaris' => '15:30/18:00/21:00',
        'sinopsi' => 'Un hombre insomne y un vendedor de jabón forman un club secreto de lucha.',
        'durada' => '139 min',
        'director' => 'David Fincher',
        'repartiment' => 'Brad Pitt, Edward Norton, Helena Bonham Carter',
        'qualificacio' => '+16',
        'genere' => 'Drama, Thriller',
        'trailer_url' => 'https://www.youtube.com/embed/r5KDiUNZv4w?si=V2T4D_jxRr0ngVB3',
        'estrelles' => 5
    ],
    [
        'nom' => 'Pulp Fiction',
        'imatge' => 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2023/07/pulp-fiction-3089782.jpg?tf=3840x',
        'carrusel1'=>'https://th.bing.com/th/id/OIP.WZCaOH640PBUFa_shjpdXwHaEK?rs=1&pid=ImgDetMain',
        'carrusel2'=>'https://th.bing.com/th/id/OIP.l-b7X9VJzeFODGUfcYKCTgHaDJ?rs=1&pid=ImgDetMain',
        'carrusel3'=>'https://th.bing.com/th/id/OIP.fgPy-qO5zABY5kTmMzRMjwHaD4?rs=1&pid=ImgDetMain',
        'horaris' => '15:30/18:00/21:00',
        'sinopsi' => 'La vida de dos mafiosos, un boxeador y una pareja de delincuentes se entrelazan en una serie de violentos incidentes.',
        'durada' => '154 min',
        'director' => 'Quentin Tarantino',
        'repartiment' => 'John Travolta, Uma Thurman, Samuel L. Jackson',
        'qualificacio' => '+18',
        'genere' => 'Crimen, Drama',
        'trailer_url' => 'https://www.youtube.com/embed/tGpTpVyI_OQ?si=00VfG0UveiIPmOQK',
        'estrelles' => 5
    ]
];

?>
